#! /bin/bash

# Used by ./config/systemd/user/random-wallpaper.service

WALLPAPER_DIR="${PWD}/config/wallpapers"

if ! pgrep -x swww-daemon > /dev/null; then
	swww-daemon &
	sleep 0.5
fi

WALLPAPER="$(find "$WALLPAPER_DIR" -type f | shuf -n 1)"
swww img $WALLPAPER

export CURR_WALLPAPER=$WALLPAPER
